AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-restrictions

Globals:
  Function:
    Timeout: 3

Resources:
  PostRestrictionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: restrictions.post_handler
      Runtime: python3.9


